//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

void ___gmon_start__(void);
int32_t entry_point(int32_t a1);
int32_t function_80484a0(void);
int32_t function_80484d0(int32_t a1);
int32_t function_8048580(int32_t main, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_8048600(int32_t a1);
int32_t function_8048610(void);
int32_t function_8048640(void);
int32_t function_80491e0(int32_t a1, int32_t a2, int32_t a3);
int32_t function_8049244(void);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // eax
int32_t g2 = 0; // ebx
int32_t g3 = 0;
int32_t (*g4)(int32_t) = NULL;

// ------------------------ Functions -------------------------

// Address range: 0x80484a0 - 0x80484c2
int32_t function_80484a0(void) {
    int32_t v1 = g2; // 0x80484a0
    function_8048600(v1);
    int32_t result; // 0x80484c2
    if (*(int32_t *)(g2 + 0x2b53) != 0) {
        // 0x80484b9
        __gmon_start__();
        int32_t * v2;
        result = (int32_t)&v2;
        // branch -> 0x80484be
    } else {
        result = 0;
    }
    // 0x80484be
    g2 = v1;
    return result;
}

// Address range: 0x80484d0 - 0x804857f
int32_t function_80484d0(int32_t a1) {
    // entry
    ((int32_t (*)(int32_t))&g4)(g3);
    function_80484d0(0);
    function_80484d0(8);
    function_80484d0(16);
    function_80484d0(24);
    function_80484d0(32);
    function_80484d0(40);
    function_80484d0(48);
    function_80484d0(56);
    function_80484d0(64);
    return function_80484d0(72);
}

// Address range: 0x8048580 - 0x80485bf
int32_t function_8048580(int32_t main, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x8048580
    __libc_start_main(main, argc, ubp_av, init, fini, rtld_fini);
    function_80484d0(80);
    function_80484d0(88);
    function_80484d0(96);
    return function_80484d0(104);
}

// Address range: 0x80485c0 - 0x80485c5
void ___gmon_start__(void) {
    // entry
    __gmon_start__();
}

// Address range: 0x80485d0 - 0x80485ff
int32_t entry_point(int32_t a1) {
    int32_t v1 = 0;
    int32_t result = __libc_start_main(0x8048edd, a1, (char **)&v1, (void (*)())0x80491e0, (void (*)())0x8049240, NULL); // 0x80485ec
    return result;
}

// Address range: 0x8048600 - 0x804860f
int32_t function_8048600(int32_t a1) {
    // 0x8048600
    g2 = a1;
    return g1;
}

// Address range: 0x8048610 - 0x804863f
int32_t function_8048610(void) {
    // 0x8048610
    return 3;
}

// Address range: 0x8048640 - 0x80491df
int32_t function_8048640(void) {
    // 0x8048640
    return 0;
}

// Address range: 0x80491e0 - 0x804923c
int32_t function_80491e0(int32_t a1, int32_t a2, int32_t a3) {
    // 0x80491e0
    g1 = function_8048600(g2);
    int32_t v1 = g2; // 0x80491e9
    g2 = v1 + 0x1e17;
    function_80484a0();
    int32_t result = g2 - 248; // 0x8049201
    int32_t v2 = v1 + 0x1d23 - result; // 0x8049207
    __pseudo_call(*(int32_t *)result);
    if ((v2 & -4) == 4) {
        // 0x8049235
        return result;
    }
    __pseudo_call(*(int32_t *)(g2 - 244));
    int32_t v3 = 2; // 0x804922b
    while (v3 != v2 / 4) {
        // 0x8049218
        __pseudo_call(*(int32_t *)(g2 - 248 + 4 * v3));
        v3++;
        // continue -> 0x8049218
    }
    // 0x8049235
    return result;
}

// Address range: 0x8049244 - 0x8049257
int32_t function_8049244(void) {
    // entry
    return function_8048600(g2);
}

// --------------- Dynamically Linked Functions ---------------

// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.7.2)
// Detected functions: 10
// Decompilation date: 2018-01-02 11:44:03
